[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
asset = "BwDuywJ5NxriMUEJ7EMKFth7joH3W2snbMfQtKp4nwrf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
